### PR TITLE
Reconfigure to drive with a Makefile

### PR DESCRIPTION
**Pull request by JPWKU**
Also made some adjustments to use SPDX
license identifier.  Add labels.

Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by JPWKU** [comment]
@alain2sf @Ferriera Would we need to run the _exec_bash.sh in CI after the containers are built? Or is that an end user task?

_exec_bash.sh is useless to the main repo/work. It’s just a tool to be able to easily login into containers with the CA certificate. I wrote it during QA/tests as it was more convenient than long CLI commands to remember.

I did create a .gitignore file to exclude it, did a push and it is now removed from the Github repo. No more confusion.

**Comment by alain2sf** [comment]
The _exec_bash.sh is just a convenience tool when debugging... should have
removed it from the repo to avoid confusion. You can discard it. Sorry
about that ;)

**Comment by JPWKU** [comment]
@alain2sf Can you do the same sort of refactor for reverse-proxy?  It doesn't mess with anything you all have done but gives me a simple interface to work with in CI.

**Comment by alain2sf** [comment]
Hi Jeremy,

“reverse-proxy” is handled by Tingyu so I’m not comfortable playing around
with his work. Could you double check with him, obviously I can assist
Tingyu if necessary, just keep me posted.

Thanks,
//Alain

From: Jeremy Phelps <notifications@github.com> <notifications@github.com>
Reply: edgexfoundry-holding/security-vault
<reply@reply.github.com>
<reply@reply.github.com>
Date: 22 June 2018 at 00:31:06
To: edgexfoundry-holding/security-vault <security-vault@noreply.github.com>
<security-vault@noreply.github.com>
Cc: Alain Pulluelo <alain.p@gmail.com> <alain.p@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [edgexfoundry-holding/security-vault] Reconfigure to drive
with a Makefile (#1)

@alain2sf <https://github.com/alain2sf> Can you do the same sort of
refactor for reverse-proxy? It doesn't mess with anything you all have done
but gives me a simple interface to work with in CI.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/edgexfoundry-holding/security-vault/pull/1#issuecomment-399263666>,
or mute the thread

**Review by alain2sf — APPROVED** [review]

**Pull request merged**
